// Route list for vite-ssg prerender: must match App.tsx routes
export const prerenderRoutes = [
  '/',
  '/about',
  '/services',
  '/pre-opening',
  '/experience',
  '/skills',
  '/philosophy',
  '/contact',
  '/profile',
  '/blueprint',
  '/case-studies',
  '/book',
  '/shop',
  '/products',
  '/industries',
  '/miami-restaurant-consultant',
  '/insights',

  // Case study detail pages
  '/case-studies/maska-indian-kitchen',
  '/case-studies/ve-hospitality-turnaround',
  '/case-studies/sls-brickell-banquets',
  '/case-studies/butler-hospitality-scale',

  // Insights: all 14 articles (sorted newest first)
  '/insights/labor-cost-control-caribbean',
  '/insights/labor-cost-control-latin-america',
  '/insights/labor-cost-control-europe-restaurants',
  '/insights/labor-cost-control-us-restaurants',
  '/insights/building-training-program-that-works',
  '/insights/miami-restaurant-labor-market-2026',
  '/insights/hotel-fb-why-your-restaurant-underperforms',
  '/insights/reduce-labor-cost-without-cutting-service',
  '/insights/real-cost-of-bad-pre-opening',
  '/insights/miami-pre-opening-playbook',
  '/insights/why-fractional-leadership-works',
  '/insights/pre-opening-timeline',
  '/insights/labor-cost-control-miami-restaurants',
  '/insights/what-a-fractional-gm-actually-does',
]
